import type { CrudModuleDefinition } from "../types";
import { buildDocumentModule, buildLines, buildLogs, buildRelations, buildTimeline, money } from "./shared";

export const purchaseOrdersModuleDefinition: CrudModuleDefinition = buildDocumentModule({
  view: "purchase-orders",
  title: "采购订单",
  singular: "采购订单",
  listDescription: "查看采购下单记录，承接供货需求。",
  statusTabs: ["全部单据", "待确认", "待到货", "已完成"],
  filters: [
    { key: "keyword", label: "综合搜索", type: "search", placeholder: "单号 / 供应商 / 仓库" },
    { key: "warehouse", label: "入库仓库", type: "select", options: ["全部仓库", "华北总仓", "杭州分仓", "华南中心仓"] },
    { key: "status", label: "订单状态", type: "select", options: ["全部状态", "待确认", "待到货", "已完成"] },
  ],
  columns: [
    { key: "no", label: "订单编号" },
    { key: "counterparty", label: "供应商名称" },
    { key: "warehouse", label: "收货仓库" },
    { key: "amount", label: "订单金额", align: "right", kind: "money" },
    { key: "status", label: "订单状态", kind: "status", toneKey: "statusTone" },
    { key: "handler", label: "采购员" },
    { key: "createdAt", label: "下单时间" },
  ],
  records: [
    {
      id: "po-001",
      no: "CG20250403001",
      counterparty: "苏州元禾供应链有限公司",
      warehouse: "华北总仓",
      amount: money(18240),
      status: "待到货",
      statusTone: "blue",
      handler: "沈岩",
      createdAt: "2025/04/03 08:50",
      businessDate: "2025-04-03",
      deliveryDate: "2025-04-08",
      settlement: "30天账期",
      paymentMethod: "银行转账",
      remark: "优先确保扫码设备到货。",
      internalNote: "采购入库将基于该单演示。",
      lines: buildLines("CG"),
      timeline: buildTimeline("采购订单", "采购单", "待供应商回传"),
      logs: buildLogs("采购订单"),
      relations: buildRelations("CG"),
    },
    {
      id: "po-002",
      no: "CG20250401008",
      counterparty: "宁波智链实业有限公司",
      warehouse: "杭州分仓",
      amount: money(9540),
      status: "已完成",
      statusTone: "green",
      handler: "周曼",
      createdAt: "2025/04/01 14:20",
      businessDate: "2025-04-01",
      deliveryDate: "2025-04-06",
      settlement: "现结",
      paymentMethod: "银行转账",
      remark: "常规耗材补货。",
      internalNote: "可作为采购退货上游单据。",
      lines: buildLines("CG"),
      timeline: buildTimeline("采购订单", "采购单", "已完成"),
      logs: buildLogs("采购订单"),
      relations: buildRelations("CG"),
    },
  ],
  formSections: [
    {
      title: "单据信息",
      fields: [
        { key: "no", label: "订单编号", type: "input", required: true },
        { key: "counterparty", label: "供应商名称", type: "select", required: true, options: ["苏州元禾供应链有限公司", "宁波智链实业有限公司"] },
        { key: "businessDate", label: "下单日期", type: "date", required: true },
        { key: "deliveryDate", label: "预计到货", type: "date" },
        { key: "warehouse", label: "收货仓库", type: "select", options: ["华北总仓", "杭州分仓", "华南中心仓"] },
        { key: "handler", label: "采购员", type: "input" },
        { key: "settlement", label: "结算方式", type: "select", options: ["现结", "15天账期", "30天账期"] },
        { key: "paymentMethod", label: "付款方式", type: "select", options: ["银行转账", "支付宝", "微信支付"] },
      ],
    },
    {
      title: "备注说明",
      fields: [
        { key: "remark", label: "对外备注", type: "textarea", span: 2 },
        { key: "internalNote", label: "内部说明", type: "textarea", span: 2 },
      ],
    },
  ],
  headerFields: [
    { label: "订单编号", key: "no" },
    { label: "供应商名称", key: "counterparty" },
    { label: "收货仓库", key: "warehouse" },
    { label: "订单状态", key: "status", kind: "status", toneKey: "statusTone" },
  ],
  detailSections: [
    {
      title: "单据信息",
      items: [
        { label: "订单编号", key: "no" },
        { label: "供应商名称", key: "counterparty" },
        { label: "下单日期", key: "businessDate" },
        { label: "预计到货", key: "deliveryDate" },
        { label: "收货仓库", key: "warehouse" },
        { label: "采购员", key: "handler" },
        { label: "结算方式", key: "settlement" },
        { label: "付款方式", key: "paymentMethod" },
      ],
    },
  ],
  noteKeys: { external: "remark", internal: "internalNote" },
  tags: ["待到货", "账期采购", "设备补货"],
  counterpartyLabel: "供应商名称",
});
