import type { CrudModuleDefinition } from "../types";
import { buildDocumentModule, buildLines, buildLogs, buildRelations, buildTimeline, money } from "./shared";

export const purchaseReceiptModuleDefinition: CrudModuleDefinition = buildDocumentModule({
  view: "purchase-receipt",
  title: "采购入库",
  singular: "采购入库单",
  listDescription: "查看采购入库和到货状态。",
  statusTabs: ["全部单据", "待验收", "待入库", "已入库"],
  filters: [
    { key: "keyword", label: "综合搜索", type: "search", placeholder: "单号 / 供应商 / 仓库" },
    { key: "warehouse", label: "入库仓库", type: "select", options: ["全部仓库", "华北总仓", "杭州分仓", "华南中心仓"] },
    { key: "status", label: "入库状态", type: "select", options: ["全部状态", "待验收", "待入库", "已入库"] },
  ],
  columns: [
    { key: "no", label: "入库单号" },
    { key: "counterparty", label: "供应商名称" },
    { key: "warehouse", label: "入库仓库" },
    { key: "amount", label: "入库金额", align: "right", kind: "money" },
    { key: "status", label: "入库状态", kind: "status", toneKey: "statusTone" },
    { key: "handler", label: "仓库员" },
    { key: "createdAt", label: "到货时间" },
  ],
  records: [
    {
      id: "pr-001",
      no: "RK20250403003",
      counterparty: "苏州元禾供应链有限公司",
      warehouse: "华北总仓",
      amount: money(18240),
      status: "待验收",
      statusTone: "orange",
      handler: "王晨",
      createdAt: "2025/04/03 13:12",
      businessDate: "2025-04-03",
      deliveryDate: "2025-04-03",
      settlement: "30天账期",
      paymentMethod: "银行转账",
      remark: "先清点扫码枪数量。",
      internalNote: "可直接转库存入账。",
      lines: buildLines("RK"),
      timeline: buildTimeline("采购入库", "到货单", "待仓库验收"),
      logs: buildLogs("采购入库"),
      relations: buildRelations("RK"),
    },
    {
      id: "pr-002",
      no: "RK20250402006",
      counterparty: "宁波智链实业有限公司",
      warehouse: "杭州分仓",
      amount: money(9540),
      status: "已入库",
      statusTone: "green",
      handler: "李菲",
      createdAt: "2025/04/02 11:22",
      businessDate: "2025-04-02",
      deliveryDate: "2025-04-02",
      settlement: "现结",
      paymentMethod: "银行转账",
      remark: "耗材已入库完成。",
      internalNote: "库存同步已完成。",
      lines: buildLines("RK"),
      timeline: buildTimeline("采购入库", "到货单", "已完成"),
      logs: buildLogs("采购入库"),
      relations: buildRelations("RK"),
    },
  ],
  formSections: [
    {
      title: "单据信息",
      fields: [
        { key: "no", label: "入库单号", type: "input", required: true },
        { key: "counterparty", label: "供应商名称", type: "select", required: true, options: ["苏州元禾供应链有限公司", "宁波智链实业有限公司"] },
        { key: "businessDate", label: "到货日期", type: "date", required: true },
        { key: "deliveryDate", label: "入库日期", type: "date" },
        { key: "warehouse", label: "入库仓库", type: "select", options: ["华北总仓", "杭州分仓", "华南中心仓"] },
        { key: "handler", label: "仓库员", type: "input" },
        { key: "settlement", label: "结算方式", type: "select", options: ["现结", "15天账期", "30天账期"] },
        { key: "paymentMethod", label: "付款方式", type: "select", options: ["银行转账", "支付宝", "微信支付"] },
      ],
    },
    {
      title: "备注说明",
      fields: [
        { key: "remark", label: "对外备注", type: "textarea", span: 2 },
        { key: "internalNote", label: "内部说明", type: "textarea", span: 2 },
      ],
    },
  ],
  headerFields: [
    { label: "入库单号", key: "no" },
    { label: "供应商名称", key: "counterparty" },
    { label: "入库仓库", key: "warehouse" },
    { label: "入库状态", key: "status", kind: "status", toneKey: "statusTone" },
  ],
  detailSections: [
    {
      title: "单据信息",
      items: [
        { label: "入库单号", key: "no" },
        { label: "供应商名称", key: "counterparty" },
        { label: "到货日期", key: "businessDate" },
        { label: "入库日期", key: "deliveryDate" },
        { label: "入库仓库", key: "warehouse" },
        { label: "仓库员", key: "handler" },
        { label: "结算方式", key: "settlement" },
        { label: "付款方式", key: "paymentMethod" },
      ],
    },
  ],
  noteKeys: { external: "remark", internal: "internalNote" },
  tags: ["待验收", "仓库入账", "采购到货"],
  counterpartyLabel: "供应商名称",
});
