import type { CrudModuleDefinition } from "../types";
import { buildDocumentModule, buildLines, buildLogs, buildRelations, buildTimeline, money } from "./shared";

export const salesDeliveryModuleDefinition: CrudModuleDefinition = buildDocumentModule({
  view: "sales-delivery",
  title: "销售出库",
  singular: "销售出库单",
  listDescription: "查看和执行销售出库，跟踪发货状态。",
  statusTabs: ["全部单据", "待拣货", "待复核", "已出库"],
  filters: [
    { key: "keyword", label: "综合搜索", type: "search", placeholder: "单号 / 客户 / 仓库" },
    { key: "warehouse", label: "发货仓库", type: "select", options: ["全部仓库", "华北总仓", "杭州分仓", "华南中心仓"] },
    { key: "status", label: "出库状态", type: "select", options: ["全部状态", "待拣货", "待复核", "已出库"] },
  ],
  columns: [
    { key: "no", label: "单据编号" },
    { key: "counterparty", label: "客户名称" },
    { key: "warehouse", label: "发货仓库" },
    { key: "amount", label: "单据金额", align: "right", kind: "money" },
    { key: "status", label: "出库状态", kind: "status", toneKey: "statusTone" },
    { key: "handler", label: "经手人" },
    { key: "createdAt", label: "业务时间" },
  ],
  records: [
    {
      id: "delivery-001",
      no: "CK20250403001",
      counterparty: "北京吉浓文化传媒有限公司",
      warehouse: "华北总仓",
      amount: money(5028),
      status: "待复核",
      statusTone: "orange",
      handler: "王晨",
      createdAt: "2025/04/03 10:18",
      businessDate: "2025-04-03",
      deliveryDate: "2025-04-05",
      settlement: "30天账期",
      paymentMethod: "银行转账",
      remark: "优先安排标签纸与扫码枪同车发运。",
      internalNote: "等待库内复核后过账。",
      lines: buildLines("CK"),
      timeline: buildTimeline("销售出库", "出库单", "待仓库复核"),
      logs: buildLogs("销售出库"),
      relations: buildRelations("CK"),
    },
    {
      id: "delivery-002",
      no: "CK20250402008",
      counterparty: "杭州智帆商贸有限公司",
      warehouse: "杭州分仓",
      amount: money(7740),
      status: "已出库",
      statusTone: "green",
      handler: "李菲",
      createdAt: "2025/04/02 16:02",
      businessDate: "2025-04-02",
      deliveryDate: "2025-04-03",
      settlement: "现结",
      paymentMethod: "支付宝",
      remark: "客户自提完成。",
      internalNote: "已同步签收状态。",
      lines: buildLines("CK"),
      timeline: buildTimeline("销售出库", "出库单", "已完成"),
      logs: buildLogs("销售出库"),
      relations: buildRelations("CK"),
    },
  ],
  formSections: [
    {
      title: "单据信息",
      fields: [
        { key: "no", label: "单据编号", type: "input", required: true },
        { key: "counterparty", label: "客户名称", type: "select", required: true, options: ["北京吉浓文化传媒有限公司", "杭州智帆商贸有限公司", "苏州元禾供应链有限公司"] },
        { key: "businessDate", label: "业务日期", type: "date", required: true },
        { key: "deliveryDate", label: "出库日期", type: "date" },
        { key: "warehouse", label: "发货仓库", type: "select", options: ["华北总仓", "杭州分仓", "华南中心仓"] },
        { key: "handler", label: "经手人", type: "input" },
        { key: "settlement", label: "结算方式", type: "select", options: ["现结", "15天账期", "30天账期"] },
        { key: "paymentMethod", label: "付款方式", type: "select", options: ["银行转账", "支付宝", "微信支付"] },
      ],
    },
    {
      title: "备注说明",
      fields: [
        { key: "remark", label: "对外备注", type: "textarea", span: 2 },
        { key: "internalNote", label: "内部说明", type: "textarea", span: 2 },
      ],
    },
  ],
  headerFields: [
    { label: "单据编号", key: "no" },
    { label: "客户名称", key: "counterparty" },
    { label: "发货仓库", key: "warehouse" },
    { label: "出库状态", key: "status", kind: "status", toneKey: "statusTone" },
  ],
  detailSections: [
    {
      title: "单据信息",
      items: [
        { label: "单据编号", key: "no" },
        { label: "客户名称", key: "counterparty" },
        { label: "业务日期", key: "businessDate" },
        { label: "出库日期", key: "deliveryDate" },
        { label: "发货仓库", key: "warehouse" },
        { label: "经手人", key: "handler" },
        { label: "结算方式", key: "settlement" },
        { label: "付款方式", key: "paymentMethod" },
      ],
    },
  ],
  noteKeys: { external: "remark", internal: "internalNote" },
  tags: ["待出库", "库内协同", "履约跟踪"],
  counterpartyLabel: "客户名称",
});
